image: node:latest

stages:
  - build
  - lint
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

lint:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npm run lint

#e2e-tests:
#   image: node:latest
#   stage: test
#   script:
#     - npm install
#     - npx playwright install
#     - npx playwright install-deps
#     - npm run test:playwright


pages:
  stage: deploy
  image: node:latest
  script:
    - npm install
    - npm run build
    - mv out/_next public && mv out/*.html public
  artifacts:
    paths:
      - public
